services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wms-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:RpEzPp1B9yud2sE1FKSWJ0KL3B+8G8/pdRfZ6iWBrvs=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: wms_db_test
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: K4Si9vNYmdFYtwfMrF7IR1yq9JxsrgcJXlresry5b2JdwJ4waHFZuDpwfdeUatOp
      JWT_ALGO: HS256
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wms-network

  mysql:
    image: mysql:8.0
    container_name: wms-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wms_db_test
      MYSQL_USER: wms_user
      MYSQL_PASSWORD: wms_password
    volumes:
      - wms_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wms-network

volumes:
  wms_mysql_data:
    driver: local

networks:
  wms-network:
    driver: bridge
